name: Check pull request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read
  pull-requests: write

env:
  HUSKY: 0

jobs:
  pr-validator:
    name: Run pull request checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=high

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint

      - name: Log in to Docker Hub
        uses: DEFRA/cdp-build-action/docker-login@dfb527d1bca7591fbbfd32ac007557745e888cf2 # v1.3.0

      - name: Checkout trade-gateway-local-environment
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: DEFRA/trade-gateway-local-environment
          ref: main
          path: trade-gateway-local-environment

      - name: Start trade-gateway-local-environment
        working-directory: trade-gateway-local-environment
        run: docker compose up --wait --wait-timeout 300 --quiet-pull

      - name: Set up k6
        uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1.2.1

      - name: Run smoke test
        run: npm run test

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: reports
          path: ./reports

      - name: Capture Docker Compose logs
        if: always()
        working-directory: trade-gateway-local-environment
        run: docker compose logs > logs.txt

      - name: Upload Docker Compose logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docker-compose-logs
          path: trade-gateway-local-environment/logs.txt
