name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: read
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'
  HUSKY: 0

jobs:
  build:
    if: github.run_number != 1
    name: Build, version and publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build the test suite
        uses: DEFRA/cdp-build-action/build-test@dfb527d1bca7591fbbfd32ac007557745e888cf2 # v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
